// <auto-generated />
using System;
using ATOM_CTO_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ATOM_CTO_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ATOM_CTO_API.Models.LocationPoint", b =>
                {
                    b.Property<decimal>("Latitude")
                        .HasColumnType("DECIMAL(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("DECIMAL(9,6)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.HasKey("Latitude", "Longitude");

                    b.ToTable("LocationPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
